"""
Rebuilds M_Island: sand, rock and turf, chosen per-pixel by HEIGHT and SLOPE.

The island was a vertical colour ramp - tan at the bottom, green at the top,
smoothly interpolated. From a mile off that reads as a painted hill, and from
close to it reads as nothing at all, because a beach and a cliff and a meadow
are not three shades of the same surface.

The mask is computed, not painted. The island is generated by Scripts/island.py
and has no UV story worth using (a planar XY unwrap in metres), so:

    height  : world Z above the waterline decides sand -> turf
    slope   : the world normal's Z decides ground -> rock
    the wet : a narrow band either side of the waterline is soaked sand,
              darker and glossy, which is what makes a beach meet the sea
              instead of stopping at it

Sand and turf are projected from above (world XY), which is correct for
near-flat ground and costs one sample. Rock is projected from the side (world
XZ), which is correct for the steep faces that are the only places rock shows.
No triplanar, because no surface here needs all three planes at once.
"""
import unreal

MEL = unreal.MaterialEditingLibrary
EAL = unreal.EditorAssetLibrary
AT = unreal.AssetToolsHelpers.get_asset_tools()

MAT_DIR = "/Game/Materials"
TEX_DIR = "/Game/Textures"
ISLAND = MAT_DIR + "/M_Island"
MESH = "/Game/Meshes/SM_Island"

A_IN, B_IN = ["A"], ["B"]
IN1 = ["", "Input", "VectorInput"]


def L(m):
    unreal.log("ISLEMAT " + m)


def sp(o, n, v):
    try:
        o.set_editor_property(n, v)
        return True
    except Exception as e:
        L("WARN %s: %s" % (n, str(e)[:80]))
        return False


def build():
    if EAL.does_asset_exist(ISLAND):
        EAL.delete_asset(ISLAND)
    mat = AT.create_asset("M_Island", MAT_DIR, unreal.Material,
                          unreal.MaterialFactoryNew())

    def expr(cls, x, y):
        return MEL.create_material_expression(mat, cls, x, y)

    def link(a, ao, b, pins):
        for p in pins:
            if MEL.connect_material_expressions(a, ao, b, p):
                return True
        L("WARN link %s->%s %s" % (a.get_name(), b.get_name(), pins))
        return False

    def scalar(name, v, x, y):
        n = expr(unreal.MaterialExpressionScalarParameter, x, y)
        sp(n, "parameter_name", name)
        sp(n, "default_value", v)
        sp(n, "group", "Island")
        return n

    def vector(name, c, x, y):
        n = expr(unreal.MaterialExpressionVectorParameter, x, y)
        sp(n, "parameter_name", name)
        sp(n, "default_value", c)
        sp(n, "group", "Island")
        return n

    def const(v, x, y):
        n = expr(unreal.MaterialExpressionConstant, x, y)
        n.set_editor_property("r", v)
        return n

    def add(a, b, x, y, ao="", bo=""):
        n = expr(unreal.MaterialExpressionAdd, x, y)
        link(a, ao, n, A_IN)
        link(b, bo, n, B_IN)
        return n

    def mul(a, ao, b, bo, x, y):
        n = expr(unreal.MaterialExpressionMultiply, x, y)
        link(a, ao, n, A_IN)
        link(b, bo, n, B_IN)
        return n

    def sub(a, b, x, y, ao="", bo=""):
        n = expr(unreal.MaterialExpressionSubtract, x, y)
        link(a, ao, n, A_IN)
        link(b, bo, n, B_IN)
        return n

    def div(a, b, x, y, ao="", bo=""):
        n = expr(unreal.MaterialExpressionDivide, x, y)
        link(a, ao, n, A_IN)
        link(b, bo, n, B_IN)
        return n

    def mask(src, x, y, r, g, b, so=""):
        n = expr(unreal.MaterialExpressionComponentMask, x, y)
        sp(n, "r", r); sp(n, "g", g); sp(n, "b", b); sp(n, "a", False)
        link(src, so, n, IN1)
        return n

    def sat(src, x, y, so=""):
        n = expr(unreal.MaterialExpressionClamp, x, y)
        sp(n, "min_default", 0.0)
        sp(n, "max_default", 1.0)
        link(src, so, n, IN1 + ["Input"])
        return n

    def lerp(a, b, al, x, y, ao="", bo="", alo=""):
        n = expr(unreal.MaterialExpressionLinearInterpolate, x, y)
        link(a, ao, n, A_IN)
        link(b, bo, n, B_IN)
        link(al, alo, n, ["Alpha"])
        return n

    def absn(src, x, y, so=""):
        n = expr(unreal.MaterialExpressionAbs, x, y)
        link(src, so, n, IN1)
        return n

    def tex(name, asset, uv, x, y, normal=False):
        n = expr(unreal.MaterialExpressionTextureSampleParameter2D, x, y)
        sp(n, "parameter_name", name)
        sp(n, "group", "Island")
        t = EAL.load_asset(TEX_DIR + "/" + asset)
        if t is None:
            L("MISSING texture %s" % asset)
        sp(n, "texture", t)
        if normal:
            sp(n, "sampler_type", unreal.MaterialSamplerType.SAMPLERTYPE_NORMAL)
        link(uv, "", n, ["UVs", "Coordinates"])
        return n

    # ------------------------------------------------------------ inputs
    world = expr(unreal.MaterialExpressionWorldPosition, -2800, 0)
    wz = mask(world, -2600, 220, False, False, True)

    scale = scalar("GroundScaleCm", 700.0, -2800, 140)
    uv_all = div(world, scale, -2600, 0)
    uv_top = mask(uv_all, -2400, -100, True, True, False)    # x, y
    uv_side = mask(uv_all, -2400, 60, True, False, True)     # x, z

    normal_ws = expr(unreal.MaterialExpressionVertexNormalWS, -2800, 400)
    nz = absn(mask(normal_ws, -2600, 400, False, False, True), -2450, 400)

    # ---------------------------------------------------------- the masks
    # Rock where it is steep. A beach is flat, a cliff is not, and nothing else
    # has to be authored for the two to separate correctly on a generated hill.
    rock_at = scalar("RockSlopeStart", 0.80, -2600, 520)
    rock_fade = scalar("RockSlopeFade", 0.22, -2600, 600)
    rock_m = sat(div(sub(rock_at, nz, -2300, 480), rock_fade, -2150, 480),
                 -2000, 480)

    # Turf above the strand line, sand below it.
    sand_top = scalar("SandTopCm", 320.0, -2600, 720)
    sand_fade = scalar("SandFadeCm", 260.0, -2600, 800)
    turf_m = sat(div(sub(wz, sand_top, -2300, 700), sand_fade, -2150, 700),
                 -2000, 700)

    # And the wet strand: a band hugging the waterline, on BOTH sides, because
    # the sea is never still and the sand it just left is still dark.
    wet_top = scalar("WetSandTopCm", 90.0, -2600, 940)
    wet_fade = scalar("WetSandFadeCm", 150.0, -2600, 1020)
    wet_m = sat(div(sub(wet_top, wz, -2300, 920), wet_fade, -2150, 920),
                -2000, 920)

    # --------------------------------------------------------- the albedo
    sand_c = tex("SandC", "T_Sand_C", uv_top, -1700, -400)
    turf_c = tex("TurfC", "T_Turf_C", uv_top, -1700, -100)
    rock_c = tex("RockC", "T_Rock_C", uv_side, -1700, 200)

    ground_c = lerp(sand_c, turf_c, turf_m, -1350, -250)
    all_c = lerp(ground_c, rock_c, rock_m, -1100, -150)

    soak = vector("WetSandTint", unreal.LinearColor(0.46, 0.42, 0.38, 1.0),
                  -1350, 100)
    # Only the SAND gets soaked; wetting the turf would put a dark ring round
    # the island wherever the hill happens to be steep at the waterline.
    sand_only = sub(scalar("One", 1.0, -1700, 1100), turf_m, -1500, 1050)
    wet_eff = mul(mul(wet_m, "", sat(sand_only, -1350, 1050), "", -1200, 950),
                  "", scalar("WetSandAmount", 1.0, -1200, 1080), "", -1050, 950)
    wet_c = mul(all_c, "", soak, "", -850, 50)
    base = lerp(all_c, wet_c, wet_eff, -600, -100)

    # Macro variation, tiled at tens of metres. The ground textures tile every
    # seven, which is under a pixel at two hundred metres and averages to one
    # flat colour - which is exactly what the capture showed. This one survives
    # the distance because its features are bigger than the distance shrinks.
    mscale = scalar("MacroScaleCm", 9000.0, -2100, 1250)
    muv = mask(div(world, mscale, -1900, 1200), -1750, 1200, True, True, False)
    mtex = tex("MacroMask", "T_Macro_M", muv, -1600, 1200)
    mlo = scalar("MacroLow", 0.68, -1600, 1360)
    mhi = scalar("MacroHigh", 1.22, -1600, 1440)
    macro = lerp(mlo, mhi, mtex, -1350, 1250)
    varied = mul(base, "", macro, "", -560, -100)

    tint = vector("IslandTint", unreal.LinearColor(1.0, 1.0, 1.0, 1.0), -850, 200)
    MEL.connect_material_property(mul(varied, "", tint, "", -380, -100), "",
                                  unreal.MaterialProperty.MP_BASE_COLOR)

    # --------------------------------------------------------- the normal
    #
    # THE PROJECTION AND THE FRAME HAVE TO BE THE SAME PAIR OF AXES. The island
    # does have UVs - island.py writes a top-down (x, y) layout - so the tangent
    # frame the engine builds has its U along world X and its V along world Y.
    # Sand and turf are sampled with uv_top, the same (x, y), so they agreed.
    # The ROCK is sampled with uv_side, (x, z): its green channel means "slope
    # along +Z" and was being applied along +-Y, a median 75 degrees out on the
    # rock faces, on a map whose relief is deliberately banded strata.
    #
    # Rebuilt the same way as the ship's master: each sample is a height
    # gradient in its own projection's axes, the gradients are blended by the
    # masks that already exist, the part along the surface normal is removed,
    # and what is left tilts the geometric normal. Nothing here is forced by a
    # missing UV set - the island has one - but a projection and a frame that
    # disagree is the same defect wherever it happens.
    sp(mat, "tangent_space_normal", False)
    if mat.get_editor_property("tangent_space_normal"):
        raise RuntimeError("M_Island: tangent_space_normal did not stick")

    sand_n = tex("SandN", "T_Sand_N", uv_top, -1700, 1400, normal=True)
    turf_n = tex("TurfN", "T_Turf_N", uv_top, -1700, 1700, normal=True)
    rock_n = tex("RockN", "T_Rock_N", uv_side, -1700, 2000, normal=True)

    zero_n = const(0.0, -1500, 1340)

    def app_n(a, b, x, y):
        n = expr(unreal.MaterialExpressionAppendVector, x, y)
        link(a, "", n, A_IN)
        link(b, "", n, B_IN)
        return n

    def grad_xy(t, x, y):
        """Sampled on (x, y): the gradient lies in X and Y."""
        return app_n(app_n(mask(t, x, y, True, False, False),
                           mask(t, x, y + 60, False, True, False), x + 150, y),
                     zero_n, x + 300, y)

    def grad_xz(t, x, y):
        """Sampled on (x, z): the gradient lies in X and Z."""
        return app_n(app_n(mask(t, x, y, True, False, False),
                           zero_n, x + 150, y),
                     mask(t, x, y + 60, False, True, False), x + 300, y)

    ground_g = lerp(grad_xy(sand_n, -1450, 1400), grad_xy(turf_n, -1450, 1700),
                    turf_m, -1000, 1550)
    all_g = lerp(ground_g, grad_xz(rock_n, -1450, 2000), rock_m, -820, 1650)

    nstr = scalar("IslandNormalStrength", 1.0, -1000, 1800)
    along = expr(unreal.MaterialExpressionDotProduct, -640, 1700)
    link(normal_ws, "", along, A_IN)
    link(all_g, "", along, B_IN)
    flat_g = sub(all_g, mul(normal_ws, "", along, "", -520, 1760), -420, 1700)
    n_world = expr(unreal.MaterialExpressionNormalize, -220, 1700)
    link(add(normal_ws, mul(flat_g, "", nstr, "", -320, 1740), -270, 1700),
         "", n_world, IN1)
    MEL.connect_material_property(n_world, "", unreal.MaterialProperty.MP_NORMAL)

    # ------------------------------------------------------ the roughness
    r_sand = scalar("SandRoughness", 0.90, -1350, 2300)
    r_turf = scalar("TurfRoughness", 0.95, -1350, 2380)
    r_rock = scalar("RockRoughness", 0.78, -1350, 2460)
    r_wet = scalar("WetSandRoughness", 0.22, -1350, 2540)
    r_ground = lerp(r_sand, r_turf, turf_m, -1050, 2320)
    r_all = lerp(r_ground, r_rock, rock_m, -850, 2380)
    MEL.connect_material_property(lerp(r_all, r_wet, wet_eff, -600, 2400), "",
                                  unreal.MaterialProperty.MP_ROUGHNESS)

    spec = scalar("Specular", 0.35, -600, 2600)
    MEL.connect_material_property(spec, "", unreal.MaterialProperty.MP_SPECULAR)

    MEL.recompile_material(mat)
    EAL.save_asset(ISLAND)
    L("built, expressions=%d" % MEL.get_num_material_expressions(mat))
    return mat


def assign(mat):
    """Re-point the mesh at it. This file DELETES and recreates M_Island, and
    SM_Island holds an object pointer, not a path - so without this the island
    keeps whatever it was holding before and the new material is never seen.
    A rebuilt material that nothing references looks exactly like a rebuilt
    material that did not work."""
    mesh = EAL.load_asset(MESH)
    if mesh is None:
        L("MISSING %s" % MESH)
        return
    mesh.set_material(0, mat)
    EAL.save_asset(MESH)
    fresh = EAL.load_asset(MESH)
    slots = fresh.get_editor_property("static_materials")
    for i, sl in enumerate(slots):
        m = sl.get_editor_property("material_interface")
        L("verify slot %d -> %s" % (i, m.get_name() if m else "NONE"))


assign(build())
L("DONE")
